version: '3'

# Each service runs in a seperate container
services:
#     # the name of the service
#     express-service:
#         # shorthand name for the container
#         container_name: Believe_it
        
#         # build path to the Dockerfile
#         build: .
        
#         # create a bind mount so local changes show up in the container
#         # for development (lots of changes - restarting the container would be slow)
#         volumes:
#             - ./:/app:Z 
        
#         # map the ports <outside container>:<inside container>
#         ports:
#             - "8100:8100"
            
#         # make sure the postgres-db-anime service starts first
#         depends_on:
#             - postgres-db-anime
        
#         # makes the value "postgres-db-anime" available in process.env.DATABASE_HOST in Node server, 
#         # so Pool connects to the container instead of localhost
#         environment:
#             DATABASE_HOST: postgres-db-anime

#         # Override the entrypoint in the Dockerfile
#         command: npm run migrate && npm run seed && npm start 

    postgres-db-anime:
        container_name: postgres-db-anime
        image: postgres:latest
        restart: always
        environment:
            DATABASE_HOST: postgres-db-anime
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_PORT: 5432
            POSTGRES_DB: NarutoCharacters
            PGDATA: /var/lib/postgresql/data
        ports:
            - "5432:5432"
        volumes:
            - pgdatasource:/var/lib/postgresql/data
            # - migration.js:/docker-entrypoint-initdb.d/migration.js


    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgAdmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: burmanbed@gmail.com
            PGADMIN_DEFAULT_PASSWORD: password
        ports:
            - "8080:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        depends_on:
            - postgres-db-anime
        
volumes:
  pgdatasource:
  pgadmin-data:

networks:
  default:

#   DATABASE_URL=postgres://shinobi_9ygt_user:LfahlwANLlkyQoV1kyi42Odfiu9fGaPF@dpg-cg2d2f82qv24hdkuutp0-a.oregon-postgres.render.com/shinobi_9ygt