version: '3'

# Each service runs in a separate container
services:
   # #the name of the service
  express-service:

    #shorthand name for the container
    container_name: Believe_it

    #build path to the Dockerfile
    build: .

    #create a bind mount so local changes show up in the container
    #for development (lots of changes - restarting the container would be slow)
    volumes: 
      - ./:/app

    #map the ports <outside container>:<inside container>
    ports: 
      - "8000:8000"

    #make sure the postgres-db service starts first
    depends_on:
        - postgres-anime

    #makes the value "prostgres-db" available in postgress.envDATABASE_HOST 
    # in Node Server, so Pool connects to the container instead of localhost
    environment:
      DATABASE_HOST: "postgres-anime"

    #Override the entrypoint in the Dockerfile
    command: ["nodemon", "project.js"]
    # the name of the service
    postgres-anime:
        container_name: postgres-anime
        image: postgres:latest
        restart: always
        environment:
            DATABASE_HOST: postgres-anime
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_PORT: 5432
            POSTGRES_DB: Naruto_Characters
            PGDATA: /var/lib/postgresql/data
        ports:
            - "5432:5432"


    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgAdmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: burmanbed@gmail.com
            PGADMIN_DEFAULT_PASSWORD: password
        ports:
            - "8080:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        depends_on:
            - postgres-anime

        
volumes:
  pgdatasource:
  pgadmin-data:
